### ISSUE TITLE
Repeated measures ANOVA error term

### ISSUE THREAD

**Issue by nuernber** [mjskay/ARTool#13]
Regarding the example [on the front page for repeated measures](https://github.com/mjskay/ARTool#alternative-model-repeated-measures-anova), it seems that other websites use an error term of `Error(Tray / (Moisture*Fertilizer))` instead of simply `Error(Tray)`. I've tried both ways for a 1-way repeated measures ANOVA and it doesn't seem to change the result. Can you explain if this is an error/bug or the expected functionality (for both 1-way and 2-way repeated measures ANOVAs)?

**Comment by mjskay** [comment]
Good question! The spec on the front page will work correctly in this particular instance. See issue #11 for a longer explanation. 

I haven't gotten around to updating the front page example to include this explanation yet (issue #11 is there to remind me to do that before the next release).

**Comment by nuernber** [comment]
Thanks!
