### ISSUE TITLE
lsmeans is leaving

### ISSUE THREAD

**Issue by rvlenth** [mjskay/ARTool#20]
Hello,

I’m writing because your R package **ARTool** suggests the **lsmeans** package. For almost a year, the new package **emmeans** has been available, and I am planning to ask the CRAN team to deprecate it in the next few months. It is quite easy to make the transition to **emmeans**. There is a vignette providing some tips for how to do this at https://cran.r-project.org/web/packages/emmeans/vignettes/transition-from-lsmeans.html, and there is even a script for converting old R sources, vignettes, and workspaces.

Please let me know if you have any questions. I will keep in touch on this matter as is necessary.

Sincerely,

Russ Lenth

**Comment by mjskay** [comment]
Thanks for the ping. I have updated the package to use emmeans instead of lsmeans and I will prepare a new CRAN submission.
