### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by RFlazcano** [mjskay/ARTool#31]
I am wondering what would be the reason beyond the message given by R for receiving this warning message:  "F values of ANOVAs on aligned responses not of interest are not all ~0. ART may not be appropriate."
Also, is there any way to address this or should the test not be used at all on data that generates this warning message?

**Comment by mjskay** [comment]
Yeah, in general if you are getting that warning you should probably consider alternative techniques. There isn't really a way to address it within ARTool.

**Comment by RFlazcano** [comment]
Besides using a non-parametric alternative to a one-way ANOVA are there any other non-parametric alternatives that generate an interaction term? I have not been able to find any besides ARTool.

**Comment by mjskay** [comment]
You could look into ordinal regression, which can be used on both discrete outcomes and continuous outcomes.

See here: https://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/

Or here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5675816/
