### ISSUE TITLE
Ensuring correctness - checking for effect stripping on aligned data

### ISSUE THREAD

**Issue by mverce** [mjskay/ARTool#33]
I asked about this 5 days ago on StackExchange/CrossValidated but I am afraid the question got buried before anyone who could answer it saw it, so I hope you don't mind me asking here.

I tried using ART ANOVA recently for two-way analyses, but `summary.art` keeps warning me that "F values of ANOVAs on aligned responses not of interest are not all ~0". According to Wobbrock _et al._, 2011, this indicates imperfect stripping of the effects that are not the one being aligned for. From what I understand the `summary.art` compares the values to 0 using `all.equal` with the default tolerance, which is sqrt(.Machine$double.eps). This is ca. 1.5*10-8.

For example, I am getting this warning even when the maximum F-value after ANOVA on aligned responses is 0.0003. ANOVA with 'response="aligned"' shows that these non-zero F-values occurred in the case of aligning by interactions. For some dependent variables, this F-value reaches 0.07.

Am I doing something wrong to get these F-values that are not exactly 0? Is it reasonably normal to get such values and the comparison is just excessively strict? How far from 0 can one get before the results of ART ANOVA start getting unreliable? In what way do they become less reliable? I would really appreciate any information, context, or pointer!

**Comment by mjskay** [comment]
Unfortunately I'm not aware of work looking at the impact of imperfect stripping or at what magnitude it really becomes a problem (hence the conservative approach taken in ARTool). Thus, at the moment I can't offer better advice than to consider other approaches, at the very least as a robustness check.

**Comment by mverce** [comment]
Thank you for the quick reply! I've noticed that it is possible to reach F = 0 in my data set by equalizing the samples sizes by omitting some units, so sample size imbalance could be the culprit. 

I'll have a look around if I can find any more suitable alternatives.

**Comment by mjskay** [comment]
No prob, sorry I couldn't be more help.
