### ISSUE TITLE
How to perform contrast tests with mixed design? 

### ISSUE THREAD

**Issue by minhengw** [mjskay/ARTool#39]
Hi, 

I am reading your vignette "Contrast tests with ART" (2021 version). The example used seems a between-subject factorial design. 

I am running similar contrast tests, but my experiment is mixed design (one is between-subject factor, and the other is a within-subject design). When using package 'phia' to analyze the pairwiese comparison for interaction (the difference of differences), the statistic is "chisq", instead of t or F value. If that normal? thanks!

**Comment by mjskay** [comment]
Our [paper on contrast tests with ART](https://doi.org/10.1145/3472749.3474784) (pdf [here](https://faculty.washington.edu/wobbrock/pubs/uist-21.pdf)) looked at between and within designs, but not mixed designs. I'd look there and see if it covers your use cases, but if not I'd suggest running some simulations to see if it correctly recovers effects for your design.
