### ISSUE TITLE
Rstudio crashes when apply anova(m)

### ISSUE THREAD

**Issue by mtsiknia** [mjskay/ARTool#40]
Hi

I am experiencing a strange error, and I am not sure if it a problem with ARTool library or Rstudio.

I run my model, e.g.
m<-art(Y ~ X1 * X2 * X3 + (1|RE), data=data) without any problem, m object exists in my environment and it looks OK,
but when I try anova(m) or art.con(m) R studio crashes and gives the following error: 
[509935:509935:20240121,232749.348089:ERROR elf_dynamic_array_reader.h:61] tag not found
[509935:509935:20240121,232749.348089:ERROR elf_dynamic_array_reader.h:61] tag not found
![Screenshot from 2024-01-22 00-21-38](https://github.com/mjskay/ARTool/assets/9335419/de2c0218-132b-4f64-b4b4-4573194edaff)

This error occurs only when I try to use ARTool library and not with functions from other libraries...
Any idea on the error would be very helpful!!
(..I have already tried uninstalling/reinstalling Rstudio, R and ARTool..)

My environment is 

Ubuntu 22.04.3 
R 4.3
Rstudio 2023.12.0 Build 369
ARTool v 0.11.1

Thank you!!

**Comment by mtsiknia** [comment]
Update

No problem occurred when I ran the script in Windows.
So it is an Ubuntu issue...

**Comment by mjskay** [comment]
Ah okay, closing this then as I do not think it is an ARTool problem.
