### ISSUE TITLE
No values in "F values of ANOVAs on aligned responses not of interest (should all be ~0):"

### ISSUE THREAD

**Issue by Sarang-Jokhio** [mjskay/ARTool#41]
Hello. I applied art to data having observations from 30 subjects. The dependent variable is ranged between 0 - 100 and independent variable has 3 levels.

art_m_block2<- art(Percentage.Executed.Lane.Changes ~ Adjacant.Gap + (1|Subject.Number), data = data)

- Subject.Number is factor representing number of subjects
- Adjacant.Gap (Independent Variable) is factor with 3 levels
- Percentage.Executed.Lane.Changes is numeric with range 0-100.

After fitting the art, I printed a summary
##Print Summary
summary(art_m_block2)

Is the output correct? When I applied art on Higgins1990Table5, I got 0s in F values of ANOVAs on aligned responses, not of interest (should all be ~0). However, in my model, there are no values. What Am I missing? 

Thank you so much for your time.

Here is the output of summary(art_m_block2)

Aligned Rank Transform of Factorial Model

Call:
art(formula = Percentage.Executed.Lane.Changes ~ Adjacant.Gap + 
    (1 | Subject.Number), data = data)

Column sums of aligned responses (should all be ~0):
Adjacant.Gap 
           0 

F values of ANOVAs on aligned responses not of interest (should all be ~0):
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.

**Comment by mjskay** [comment]
Ah, that's because you have only one fixed effect on the righthand side, so there isn't anything to list there. Should be fine.
