### ISSUE TITLE
Publication-ready tables 

### ISSUE THREAD

**Issue by alibezzaa** [mjskay/ARTool#42]
Hello, 

First of all, I would like to thank you for this wonderful package. I found no bugs, I only have an issue concerning the publication of the results tables from the anova(art object) function. Is there an easy way to produce the output in a publication-ready format ?

Cheers.

**Comment by mjskay** [comment]
Not sure what you mean by publication-ready format?

**Comment by alibezzaa** [comment]
Hello,

I mean APA style tables.
________________________________
De : Matthew Kay ***@***.***>
Envoyé : samedi 6 avril 2024 16:34
À : mjskay/ARTool ***@***.***>
Cc : Ali BEZZAA ***@***.***>; Author ***@***.***>
Objet : Re: [mjskay/ARTool] Publication-ready tables (Issue #42)


Not sure what you mean by publication-ready format?

**Comment by mjskay** [comment]
Ah --- unfortunately tables for specific publication formats are out of the scope of this package. `anova()` on an `art` object produces a data frame, which you should be able to use with other packages designed to produce tables in specific formats (a quick google suggests maybe [rempsyc](https://rempsyc.remi-theriault.com/articles/table) for APA tables though I haven't used it before).
